# Generated by Django 3.1.2 on 2020-10-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_number', models.IntegerField(verbose_name='Number')),
                ('fibonacci_number', models.IntegerField(blank=True, null=True, verbose_name='Number fibonacci')),
            ],
        ),
    ]
